version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: >-
    dotnet --version

    dotnet restore "OnlineBookStoreDemo/OnlineBookStoreDemo.sln"
build:
  project: OnlineBookStoreDemo/OnlineBookStoreDemo.sln
  verbosity: minimal